version: "3.8"
services:
  docker-api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    container_name: "docker-api-container"
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/app
